# Generated by Django 4.1.3 on 2022-11-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0002_horario_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviar_msg', models.BooleanField(auto_created=True, default=True)),
                ('endereco', models.CharField(max_length=200)),
                ('gerar_disponibilidade', models.CharField(choices=[(1, 'Um dia'), (3, 'Três dias'), (7, 'Uma semana dias'), (30, 'Um mês')], default=1, max_length=20)),
                ('horarios', models.ManyToManyField(related_name='configuracao_horario', to='horarios.horario')),
            ],
        ),
    ]
