# Generated by Django 4.1.3 on 2022-11-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fidelidade', models.BooleanField(auto_created=True, default=False, verbose_name='Plano fidelidade')),
                ('agendamento', models.BooleanField(auto_created=True, default=True, verbose_name='Aberto para agendamento')),
                ('enviar_msg', models.BooleanField(auto_created=True, default=True, verbose_name='Enviar mensagem automaticas')),
                ('validade', models.IntegerField(default=0, verbose_name='Quantidade em dias para a valide da fidelização')),
                ('quantidade_fidelidade', models.IntegerField(default=0, verbose_name='Qntd de serviços concluidos para completar a fidelização')),
                ('endereco', models.CharField(max_length=200)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('whatsapp', models.CharField(max_length=11)),
                ('celular', models.CharField(max_length=11)),
                ('gerar_disponibilidade', models.CharField(choices=[(1, 'Um dia'), (3, 'Três dias'), (7, 'Uma semana dias'), (30, 'Um mês')], default=1, max_length=20)),
                ('horarios', models.ManyToManyField(related_name='configuracao_horario', to='horarios.horario')),
            ],
        ),
    ]
