# Generated by Django 4.1.3 on 2022-11-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='agendamento',
            field=models.BooleanField(auto_created=True, default=True, verbose_name='Aberto para agendamento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='celular',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracao',
            name='fidelidade',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='Plano fidelidade'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='quantidade_fidelidade',
            field=models.IntegerField(default=0, verbose_name='Qntd de serviços concluidos para completar a fidelização'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='validade',
            field=models.IntegerField(default=0, verbose_name='Quantidade em dias para a valide da fidelização'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='whatsapp',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='enviar_msg',
            field=models.BooleanField(auto_created=True, default=True, verbose_name='Enviar mensagem automaticas'),
        ),
    ]
