# Generated by Django 4.1.3 on 2023-04-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_configuracao_grupos_permissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='agendamento',
            field=models.BooleanField(auto_created=True, default=True, verbose_name='Disponível para agendamento'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='grupos_permissao',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='Grupos de permissões padrão criados'),
        ),
    ]
