# Generated by Django 4.1.3 on 2023-04-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_alter_configuracao_agendamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='gerar_disponibilidade',
            field=models.IntegerField(choices=[(1, 'Um dia'), (3, 'Três dias'), (7, 'Uma semana dias'), (30, 'Um mês')], default=1),
        ),
    ]
