# Generated by Django 4.1.3 on 2022-11-05 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelado', models.BooleanField(auto_created=True, default=False)),
                ('concluido', models.BooleanField(auto_created=True, default=False)),
                ('ativo', models.BooleanField(auto_created=True, default=True)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.servico')),
            ],
            options={
                'unique_together': {('data', 'horario')},
            },
        ),
    ]
