# Generated by Django 4.1.3 on 2023-04-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='protocolo',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Protocolo'),
            preserve_default=False,
        ),
    ]
