# Generated by Django 4.1.3 on 2022-11-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
    ]
