# Generated by Django 4.1.3 on 2023-04-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='titulo',
            field=models.CharField(default=1, max_length=400, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(auto_created=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=400, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor'),
        ),
    ]
