# Generated by Django 4.1.3 on 2022-11-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horarios', models.ManyToManyField(related_name='disponibilidade_horario', to='horarios.horario')),
            ],
        ),
    ]
