# Generated by Django 4.1.3 on 2023-04-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='ativo',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
