# Generated by Django 4.1.3 on 2022-11-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_horario_ativo'),
        ('disponibilidades', '0002_remove_disponibilidade_horarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='horarios',
            field=models.ManyToManyField(related_name='disponibilidade_horario', to='horarios.horario'),
        ),
    ]
