# Generated by Django 4.1.3 on 2022-11-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_full', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=11)),
            ],
            options={
                'unique_together': {('whatsapp',)},
            },
        ),
    ]
