# Generated by Django 4.1.3 on 2022-11-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='ativo',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
